import type { Metadata } from "next";
import { Roboto } from "next/font/google"
import "./globals.css";
import { ModalProvider } from "./_context/ModalContext";
import ModalAtom from "./_components/atoms/ModalAtom";
import NavbarOrganism from "./_components/organisms/NavbarOrganism";

const roboto = Roboto({ weight: "400", subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider>
        <body className={`${roboto.className} relative`}>
          <ModalAtom />
          <NavbarOrganism />
          {children}
        </body>
      </ModalProvider>
    </html>
  );
}
