import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "./_context/ModalContext";
import ModalAtom from "./_components/atoms/ModalAtom";
import CardAtom from "./_components/atoms/CardAtom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ModalProvider>
        <body className={`${inter.className} relative`}>
          <ModalAtom />
          {children}
        </body>
      </ModalProvider>
    </html>
  );
}
